openapi: 3.0.1
info:
  title: vector-tiles-rasterizer
  description: A proxy server for rasterizing vector tiles
  version: 1.0.0
  license:
    name: BSD-2-Clause
    url: https://opensource.org/licenses/BSD-2-Clause

paths:
  /{z}/{x}/{y}.png:
    get:
      operationId: getTiles
      tags:
        - rasterize
      summary: get raster tiles by z, x, y
      parameters:
        - in: path
          name: 'z'
          required: true
          schema:
            allOf:
              - $ref: '#/components/schemas/tilePosition'
              - maximum: 22
          description: zoom level
        - in: path
          name: 'x'
          required: true
          schema:
            $ref: '#/components/schemas/tilePosition'
          description: x axis tile
        - in: path
          name: 'y'
          required: true
          schema:
            $ref: '#/components/schemas/tilePosition'
          description: y axis tile
      responses:
        200:
          description: the requested rasterized image
          content:
            image/png:
              schema:
                type: string
                format: binary
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/UnexpectedError'
components:
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/error'
              - properties:
                  statusCode:
                    enum:
                      - 400
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/error'
              - properties:
                  statusCode:
                    enum:
                      - 404
    UnexpectedError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  schemas:
    tilePosition:
      type: number
      format: int32
      default: 0
      minimum: 0
    error:
      type: object
      required:
        - message
        - error
        - statusCode
      properties:
        message:
          type: string
        error:
          type: string
        statusCode:
          type: number
          format: int32
