{{- $releaseName := .Release.Name -}}
{{- $chartName := include "vector-tiles-rasterizer.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-style-configmap
data:
{{ (.Files.Glob "configurations/styles/**.json").AsConfig | indent 2}}
{{- end -}}
