name: pull_request

on: [pull_request]

jobs:
  eslint:
    name: Run eslint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          prettier: true
          eslint_extensions: ts

      - name: OpenAPI Lint Checks
        uses: nwestfall/openapi-action@v1.0.2
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         file: ./openapi3.yaml

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      tileserver-gl:
        image: maptiler/tileserver-gl:v3.1.1
        ports:
          - 80:80
        options: >-
          --user 0
          --health-cmd "node -e 'const http = require(\"http\"); const req = http.get(\"http://localhost:80\", function (res) { const { statusCode } = res; if (statusCode !== 200) { process.exit(1); }; req.on(\"error\", function (e) { process.exit(1); })});'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        node: [12.x, 14.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Build test docker image
        run: docker build --build-arg NODE_VERSION=${{ matrix.node }} -f ./tests.Dockerfile -t vector-tiles-rasterizer-tests:latest .

      - name: Run tests
        run: docker run --network host vector-tiles-rasterizer-tests:latest

      - uses: actions/upload-artifact@v2
        with:
          name: Test Reporters
          path: reports/**
